### PR TITLE
Fix issue 754: rest_forbidden as an second author

### LINKED ISSUE #754: rest_forbidden as an second author
When I try to edit a post with an assigned second author, I get the error message "rest_forbidden":

`code: "rest_forbidden"
data: Object { status: 403 }
​message: "Sorry, you are not allowed to do that."`

I have already isolated the plugin (deactivated all other plugins one after the other and also for themes), but just can't find a problem. Anyone an idea?

### PR DESCRIPTION
**Pull request by htdat**
Fix #754 

## Description 

The explanation for this fix is here https://github.com/Automattic/Co-Authors-Plus/issues/754#issuecomment-803546624

## Test 

1) Create author user
2) Create draft with admin user and add author user to draft
3) Attempt to access draft from author user
4) The co-author can edit the draft normally 
5) There is no `403` XHR request in the browser console

### CODE REVIEW

**Comment by nielslange** [comment]
Thanks for spinning up this PR, @htdat! 🙌 I tested it on my local environment and the PR looks great. I just noticed one case in which the PR does not work as expected yet. The PR works great when the co-author is an `admin`, an `editor` or an `author`. However, when the co-author is a `contributor`, the co-author cannot edit a scheduled post. While the scheduled post is visible, it's displayed write-protected.

### Author viewing a scheduled post

Screenshot 2021-03-22 at 10 53 20

### Contributor viewing a scheduled post

Screenshot 2021-03-22 at 10 53 39

I also updated the permission table from https://github.com/Automattic/Co-Authors-Plus/issues/754#issuecomment-797456893. These are the permissions when applying your PR.

### Author

<table>
	<tr>
		<th></th>
		<th colspan="2">Block Editor</th>
		<th colspan="2">Classic Editor</th>
	</tr>
	<tr>
		<th></th>
		<th>before PR</th>
		<th>after PR</th>
		<th>before PR</th>
		<th>after PR</th>
	</tr>
	<tr>
		<td>Author can edit drafted post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Author can edit pending post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Author can edit scheduled post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Author can edit published post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Author can edit private post</td>
		<td align="center">❌</td>
		<td align="center">❌</td>
		<td align="center">❌</td>
		<td align="center">❌</td>
	</tr>
	<tr>
		<td>Author can edit protected post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
</table>

### Contributor

<table>
	<tr>
		<th></th>
		<th colspan="2">Block Editor</th>
		<th colspan="2">Classic Editor</th>
	</tr>
	<tr>
		<th></th>
		<th>before PR</th>
		<th>after PR</th>
		<th>before PR</th>
		<th>after PR</th>
	</tr>
	<tr>
		<td>Contributor can edit drafted post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Contributor can edit pending post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Contributor can edit scheduled post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Contributor can edit published post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Contributor can edit private post</td>
		<td align="center">❌</td>
		<td align="center">❌</td>
		<td align="center">❌</td>
		<td align="center">❌</td>
	</tr>
	<tr>
		<td>Contributor can edit protected post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
</table>

**Review by nielslange — COMMENTED** [review]
~Great PR, @htdat. Well done. 🙌 I just found one case that isn't working yet, which I explained in detail in https://github.com/Automattic/Co-Authors-Plus/pull/757#issuecomment-803743616. It would be great if we could solve this case as well, so that both the behaviour of the block and the classic editor is in synch.~

**Review by nielslange — APPROVED** [review]
Please ignore my previous comment. I double-checked the initial settings and your PR works exactly as expected. Well done.

**Comment by nielslange** [comment]
@rebeccahum Would you mind reviewing @htdat's PR to check if it can be merged?

**Review by rebeccahum — APPROVED** [review]
Thanks, @htdat. This works great and your explanation is 💯 spot-on!

**Pull request merged**
