### PR TITLE
Author select improvements

### PR DESCRIPTION
**Pull request by Ritesh-patel**
## Description

This PR makes some improvements to author selection box.

- Use debounce to delay author search request
- Fix long author names overlapping with icons

Should include any special considerations, decisions, and links to relevant GitHub issues.

Please don't include internal or private links

## Deploy Notes

No dependencies.

## Steps to Test

Outline the steps to test and verify the PR here.

- Monitor author search request after search keyword is inputted
- Add a guest author with very long name, it shouldn't overlap with the move and close icons in author select panel

### CODE REVIEW

**Comment by jeffpaul** [comment]
@rebeccahum any chance you can help route this for review/merging on your end?  🙏🏼

**Comment by rebeccahum** [comment]
Thanks! In my testing though, I am still seeing it overlap with the icon:
Screenshot 2023-02-17 at 11 51 49 AM

**Comment by Ritesh-patel** [comment]
@rebeccahum thanks for checking this PR, I have pushed a commit which should fix the author name overlap issue.

**Review by rebeccahum — APPROVED** [review]
Thanks!

**Pull request merged**
