### PR TITLE
Modify phpcs ruleset

### PR DESCRIPTION
**Pull request by smistephen**
The current phpcs ruleset is outdated (see #577). This commit updates it to the modern one.

The new build process has been tested successfully, you can see it passing here:
https://travis-ci.com/smistephen/Co-Authors-Plus/builds/80303610

### CODE REVIEW

**Comment by GaryJones** [comment]
The change here makes sense, in so much as the `WordPress-VIP` ruleset is deprecated, but what remains in Travis is still odd - PHPCompatibility is cloned, for instance, but the Travis script only runs PHPCS against the `WordPressVIPMinimum` standard.

Ideally, along with #541 (which needs updating), the PHPCS config would be handled in `.phpcs.xml.dist`, and then Travis can just call `phpcs` with no flags, so it is consistent to running it locally.

**Comment by smistephen** [comment]
Sounds good. @paulschreiber I'd be fine with closing this small PR if you integrated my changes into your larger one :)

**Comment by paulschreiber** [comment]
I updated #541 based on @GaryJones' suggestions. Let me know if anything else needs to be changed.

**Comment by smistephen** [comment]
@paulschreiber Could you also modify the Travis file in your PR? It's a super small change and then I'll close this PR:

https://github.com/Automattic/Co-Authors-Plus/pull/579/files

**Comment by smistephen** [comment]
Or, as @GaryJones suggested, you could modify the `phpcs.xml` file, that works too

**Comment by smistephen** [comment]
I can't see the changes, the last commit I can view is from late June?

https://github.com/Automattic/Co-Authors-Plus/pull/541/commits

Maybe it's a problem with my account. @GaryJones can you see them? :(

**Comment by paulschreiber** [comment]
I'm not seeing the changes in the PR, either. Seeing updates in https://github.com/Automattic/liveblog/pull/486.

**Comment by nielslange** [comment]
Closing this PR as the corresponding rule set had been updated accordingly in https://github.com/Automattic/Co-Authors-Plus/pull/751.

**Pull request closed without merging**
