### PR TITLE
Removing check for is_user_member_of_blog 

### PR DESCRIPTION
**Pull request by bcampeau**
I've discussed this issue a few times, but this line of code really breaks the spirit of Co-Authors Plus. Guest authors don't have to be users, so why should they be required to be a member of the blog to have an author archive page? I also have legit use cases (i.e. NY Post sites) where this breaks their author pages.

### CODE REVIEW

**Comment by maxfenton** [comment]
+1 — the requirement that the user is a member of the blog broke the logic on the author pages of a site I'm working on. Any chance this (or other) pull requests will get merged anytime soon? Looks like this has been in the queue for many months.

**Comment by maxfenton** [comment]
@natebot Thank you so much. I'm new to this plugin (and community), so I'm delighted to see development is alive and well. Stoked to see this pull request after looking at issue #201.

**Comment by joshbetz** [comment]
From: 2ce2ce8

> The author archive should be displayed when the user is a member of the blog, or the user has a previously published post on the blog.

I think we have to keep this. If a user is not a member of a site and doesn't have any posts, they shouldn't have an author page. Think about big multisite environments like WordPress.com. To use the NY Post example, http://nypost.com/author/betzster should be a 404 page rather than an empty author page.

**Comment by maxfenton** [comment]
@joshbetz That makes perfect sense. I was having missing pages for guest authors with published posts, so maybe my problem lies somewhere else.

**Comment by mattoperry** [comment]
Some thoughts:

- sometimes it's undesirable for guest authors to have an author page ... for example, if a public figure writes a one-time op-ed on a site, it's not clear that there should be an author archive for that author.
- on the other hand, if a guest author (even if not a member) has 1000 posts or something, you'd kind of expect an author page.
- we should avoid empty archive pages ... archives for normal WP authors with no posts 404 .. seems like the same thing should happen here (perhaps it already does)
- @joshbetz is there anything in particular you're worried about breaking if this is introduced?  One thing to note is that this is already merged on .com, just not in the public version of the plugin.

Just spoke to @natebot and we'd like to bump this from the release we're doing this week since it's just meant to be a maintenance/sync release, and we should probably a) only include very safe changes and b) consider this a bit more.  Doing this will allow us to sync .com and github, with the exception of this change, and then move on to a larger release that could include this in the coming weeks.

**Pull request merged**
