### PR TITLE
BUGFIX regular expression in posts_where_filter()

### PR DESCRIPTION
**Pull request by ghost**
According to issue #573 the error is, when the user_id of the currently logged in user is a prefix of the user_id queried for archive pages. This effects archive pages in frontend, when logged in and the posts archives in backend.

For example: the logged in user_id is 1 and the user_id for displaying the archive is 16

AND ((posts.post_author = 16

will be substituted to

AND ((term_taxonomy.taxonomy = 'author' AND term_taxonomy.term_id = '243' 6

This produces a sql error and the query is empty.

### CODE REVIEW

**Comment by jtbayly** [comment]
Awesome! Hope to see this in the next update.

**Comment by TheCrowned** [comment]
Thanks a lot for your contribution! Just wanted to leave a note to say I tested this, and works for me :)

**Comment by jtbayly** [comment]
Just tested this and it works as described. Fixes issue #573 also.

Really needs to be merged, in my opinion.

**Comment by rebeccahum** [comment]
I was able to reproduce, however, this didn't fix it for me.  What worked was replacing this line:

https://github.com/Automattic/Co-Authors-Plus/blob/07cbfe0eb57c00c306e3a5d441bd02a25a26dad7/co-authors-plus.php#L718

With:

`$where = preg_replace( '/(\b(?:' . $wpdb->posts . '\.)?post_author\s*=\s*(' . $id . ') )/', '(' . $maybe_both_query . ' ' . $terms_implode . ')', $where, -1 ); #' . $wpdb->postmeta . '.meta_id IS NOT NULL AND`

Perhaps I am not reproducing the issue to a 'T'?  This is on a fresh WP install with CAP however.  Is the author archive we are viewing linked to a guest author and same with the logged in user attempting to view the author archive?

**Comment by jtbayly** [comment]
I'm talking about real users, not guest authors. Perhaps there are two issues? One problem with real users and one for guest authors?

And concerning real users, I'm seeing the problem while logged in as a site admin. I'm not sure whether it matters what role the others have. Just haven't tested at that level of detail.

**Pull request merged**
