### PR TITLE
Prepare v3.2.2 release

### PR DESCRIPTION
**Pull request by philipjohn**
Full changeset for this release: https://github.com/Automattic/Co-Authors-Plus/compare/69f58e2b84927643fc382dba45d935f0477bbf7d...bd133868490f014733ebb9b7b37be65cdf17963b

### CODE REVIEW

**Comment by mjangda** [comment]
Main issue I spotted is https://github.com/Automattic/Co-Authors-Plus/pull/367#issuecomment-286642029 -- other than that, I think we're looking good.

**Comment by mjangda** [comment]
Actually, need to look at the test failures too:

```
There were 2 failures:
1) Test_Author_Queried_Object::test__author_queried_object_fix
is_archive, is_author is expected to be true. is_404 is expected to be false.
Failed asserting that false is true.
/tmp/wordpress-tests-lib/includes/testcase.php:609
/home/travis/build/Automattic/Co-Authors-Plus/tests/test-author-queried-object.php:73

2) Test_Manage_CoAuthors::test_add_coauthor_to_post
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 9
-    1 => 10
 )
```

**Comment by philipjohn** [comment]
#406 addresses the various other instances of `get_the_terms()`

> 1) Test_Author_Queried_Object::test__author_queried_object_fix

Looks like this broke with [6dbcd3cd48d29c7aa46a96269c733fb1f649dec6], see [425.9](https://travis-ci.org/Automattic/Co-Authors-Plus/jobs/179512044)

>2) Test_Manage_CoAuthors::test_add_coauthor_to_post

This one broke with [52da0aa75a1f5d93f49578686f51a6df7399c72c], see [433.9](https://travis-ci.org/Automattic/Co-Authors-Plus/jobs/210091554)

The latter is fixed by [d5305b5].

**Comment by mjangda** [comment]
> Test_Author_Queried_Object::test__author_queried_object_fix
> Looks like this broke with [6dbcd3c], see 425.9

@sboisvert @trepmal can you please take a look? ^^

**Comment by trepmal** [comment]
> The temporary tables are due to the way WordPress gets installed on the fly for testing.
> 
> https://core.trac.wordpress.org/browser/trunk/tests/phpunit/includes/testcase.php#L312 - summarized:
> 
> ```
> add_filter( 'query', function( $query ) {
> 	if ( 'CREATE TABLE' === substr( trim( $query ), 0, 12 ) ) {
> 		return substr_replace( trim( $query ), 'CREATE TEMPORARY TABLE', 0, 12 );
> 	}
> 	return $query;
> } );
> 
> ```
> 
> Interestingly (or not), we're only encountering this because we test in multisite. The initial tables that are installed are not temporary, but the subsite tables are (since those pass through the `query` filter).
> 
> If I simply comment out those filters and rerun the tests, they pass.

— https://github.com/Automattic/Co-Authors-Plus/issues/398#issuecomment-288559694

**Comment by trepmal** [comment]
I kinda missed the intro in my reply... but #398 provides the context

**Pull request merged**
