### PR TITLE
Update CLI to use cached functions

### PR DESCRIPTION
**Pull request by jasonbahl**

### CODE REVIEW

**Comment by mjangda** [comment]
Thanks for the PR, jasonbahl. Can you please provide more context around the change?

**Comment by jasonbahl** [comment]
As part of a VIP GO performance review, VIP GO pointed out several places in our codebase that weren't using cached functions, and this was part of it. I don't think these really affect our performance, but we agreed that we would adjust our controlled codebase and do our best to contribute back to plugins we don't control.

**Comment by bcampeau** [comment]
Yeah @mjangda, @emrikol requested this.

**Comment by mjangda** [comment]
👍

**Comment by mjangda** [comment]
@philipjohn I think we may need to revert this (because of #390) and explicitly pass `orderby => termorder` to the `get` calls.

**Pull request merged**
