### PR TITLE
Ensure $wp_query is as expected

### PR DESCRIPTION
**Pull request by trepmal**
Some plugins may run a query earlier than expected causing CAP's is_author() check to send up a 'called incorrectly' notice.
Patch really just does a sanity check to make sure `$wp_query` is as expected before relying on it.
Addresses #354

### CODE REVIEW

**Comment by mjangda** [comment]
This does fix the initially reported issue (i.e. the notice), but I wonder if we should actually fix the root of the problem, which feels like the plugin may not be hooking in at the ideal spot with the `fix_author_page` callback.

**Comment by trepmal** [comment]
Do you have an inkling of where that ideal spot might be? :)

It doesn't seem like there's a later hook ready and waiting that the callback can be switched to with no effort. Of course, there may be a better hook that _does_ require a little more effort...

I'll take a deeper look at what `fix_author_page` does to see where else it might work

**Comment by mjangda** [comment]
> Do you have an inkling of where that ideal spot might be? :)

I'm not totally sure :) It's a bit of a bummer that `posts_selection` doesn't pass through the query object. One of the filters like `posts_request` or `posts_results` might work, although, it would break this logic for any queries with `suppress_filters == true` (which may be okay if we document it clearly).

**Comment by sboisvert** [comment]
>although, it would break this logic for any queries with suppress_filters == true (which may be okay if we document it clearly).

I'm not sure I'm following this clearly. Would this mean that any query with suppress_filters == true would fail for is_author()?
I'm trying to think of a context where this would be used. Since get_posts() suppresses filters that's what I'd think would be the most used way that suppress_filters == true, but then would someone use is_author()?

Am I following correctly?

**Comment by mjangda** [comment]
Actually, CAP query mods don't fire when `supress_filters === true` anyway since filters like `posts_where` don't trigger.

Plus, for the `get_posts()` use case in this context, we don't really care that much anyway, since the queried object isn't accessible.

**Comment by lkraav** [comment]
Hmm, this might be superceded by https://github.com/Automattic/Co-Authors-Plus/pull/801 by now.

**Comment by nielslange** [comment]
> Hmm, this might be superceded by #801 by now.

Thanks for pointing this out, @lkraav.

**Pull request closed without merging**
