### PR TITLE
Author page SQL error (front-end and back-end)

### LINKED ISSUE #687: Author page SQL error (front-end and back-end)
Reproduction steps on a fresh WP local install:

1) Login with user ID 1 (in my case, this was the default admin account, but for illustration, we'll call it user A)
2) Create post directly from account as User A
3) Create user B with user ID of 12 (or anything that prepends with "1") and user role of "Contributor"
4) Login as user B and view author archive for User A (example.com/wp-admin/edit.php?author_name=admin) and you'll see the below error:

```
WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 AND wp_posts.post_status = 'private') GROUP BY wp_posts.ID HAVING MAX( IF ( wp' at line 1]
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id) LEFT JOIN wp_term_taxonomy ON ( tr1.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id ) WHERE 1=1 AND ((wp_posts.post_author = 1 OR (wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '12'))) AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'future' OR wp_posts.post_status = 'draft' OR wp_posts.post_status = 'pending' OR (wp_posts.post_author = 1 OR (wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '12'))1 AND wp_posts.post_status = 'private') GROUP BY wp_posts.ID HAVING MAX( IF ( wp_term_taxonomy.taxonomy = 'author', IF ( wp_term_taxonomy.term_id = '12' OR wp_term_taxonomy.term_id = '15',2,1 ),0 ) ) <> 1 ORDER BY wp_posts.post_date DESC LIMIT 0, 20
```

### PR DESCRIPTION
**Pull request by rebeccahum**
Opening new PR in lieu of #618 since that one got messy.  Fixes #687.

### CODE REVIEW

**Comment by nielslange** [comment]
@rebeccahum Can you still reproduce this problem on your end?

**Comment by rebeccahum** [comment]
@nielslange Yep, I just edited the issue, looks like user B needs to be of "Contributor" role.

**Comment by nielslange** [comment]
@rebeccahum I'm unable to reproduce the problem on my end using the following steps:

1. Create fresh WP install
2. Add `define( ‘WP_DEBUG’, true );` to wp-config.php
3. Symlink CAP plugin into test site
4. Create test post as admin (post-686)
5. Add new contributor (contributor-686)
6. Log out as admin
7. Log in as contributor
8. Head over to `/wp-admin/edit.php?author_name=admin`

Am I missing a step? Do you see the error directly on `/wp-admin/edit.php?author_name=admin`?

**Comment by rebeccahum** [comment]
@nielslange What is the ids of `contributor-686` please? It should begin with `1` (e.g. `12`)

**Comment by nielslange** [comment]
@rebeccahum The ID was indeed the problem. During my first test in an existing site, I ensured that `contributor-686` had the ID `10`, thus, starting with a `1`. When spinning up a fresh WP install, I somehow missed that step. Thanks for pointing this out.

**Review by nielslange — APPROVED** [review]
LGTM

**Pull request merged**
