### PR TITLE
Replace jQuery shorthand deprecated methods

### PR DESCRIPTION
**Pull request by rebeccahum**
Using the jQuery migrate helper, a bunch of these methods are deprecated: https://api.jquery.com/category/deprecated/

### CODE REVIEW

**Review by nielslange — CHANGES_REQUESTED** [review]
Based on https://api.jquery.com/jQuery.trim/, the jQuery function `trim()` had been deprecated with jQuery 3.5. Instead of `jQuery.trim`, the native function `String.prototype.trim()` should be used.

This counts for the following lines:
- https://github.com/Automattic/Co-Authors-Plus/blob/44fd892dc1e06b976dd48de6ba6d0687c7bdcb7b/js/co-authors-plus.js#L199
- https://github.com/Automattic/Co-Authors-Plus/blob/44fd892dc1e06b976dd48de6ba6d0687c7bdcb7b/js/co-authors-plus.js#L200
- https://github.com/Automattic/Co-Authors-Plus/blob/44fd892dc1e06b976dd48de6ba6d0687c7bdcb7b/js/co-authors-plus.js#L201
- https://github.com/Automattic/Co-Authors-Plus/blob/44fd892dc1e06b976dd48de6ba6d0687c7bdcb7b/js/co-authors-plus.js#L202
- https://github.com/Automattic/Co-Authors-Plus/blob/44fd892dc1e06b976dd48de6ba6d0687c7bdcb7b/js/co-authors-plus.js#L204
- https://github.com/Automattic/Co-Authors-Plus/blob/44fd892dc1e06b976dd48de6ba6d0687c7bdcb7b/js/co-authors-plus.js#L208

Please also see my additional question regarding the steps to test, which I mentioned in https://github.com/Automattic/Co-Authors-Plus/pull/812#issuecomment-878276611. In case I tested your changes correctly, I'd only suggest changing the function call from `jQuery.trim` to `String.prototype.trim()`. Other than that, the changes look good to me.

**Comment by nielslange** [comment]
> Using the jQuery migrate helper, a bunch of these methods are deprecated: https://api.jquery.com/category/deprecated/

@rebeccahum Can you tell me how to test this changes correctly? Here's what I did so far:

1. I installed the [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin
2. I activated to the [Twenty Ten](https://wordpress.org/themes/twentyten/) theme
3. I created a regular co-author and a guest co-author
4. I created a test post and added both the regular co-author and the guest co-author to it
5. I opened that test post in the frontend
6. I looked up the logs of the [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin via `/wp-admin/tools.php?page=jqmh&tab=logs`, but did not see any records (see screenshot below)
7. I then looked up the deprecated functions, as mentioned on https://api.jquery.com/category/deprecated/, within the [co-authors-plus.js file](https://github.com/Automattic/Co-Authors-Plus/blob/master/js/co-authors-plus.js#L208)

Here are screenshots of my settings and logs pages:

#812-settings

#812-logs

Are you seeing logs on your end? Did I miss a certain testing step to see some logs?

**Comment by rebeccahum** [comment]
I didn't use the jQuery migrate helper plugin. All you need to do is create a new post or open an existing one and look in the console logs and see warnings such as:

```
JQMIGRATE: jQuery.fn.focus() event shorthand is deprecated
```

The warnings are being thrown from https://github.com/WordPress/WordPress/blob/master/wp-includes/js/jquery/jquery-migrate.js.

**Comment by rebeccahum** [comment]
@nielslange According to the link you shared re: `.trim()`, have you tested to see if that change is compatible?

> Unlike jQuery.trim, String.prototype.trim does not work with types other than strings (null, undefined, Number).

**Comment by nielslange** [comment]
> I didn't use the jQuery migrate helper plugin. All you need to do is create a new post or open an existing one and look in the console logs and see warnings such as:
> 
> ```
> JQMIGRATE: jQuery.fn.focus() event shorthand is deprecated
> ```
> 
> The warnings are being thrown from https://github.com/WordPress/WordPress/blob/master/wp-includes/js/jquery/jquery-migrate.js.

Thanks for clarifying this, @rebeccahum. I noticed that I had to add `define( 'SCRIPT_DEBUG', true );` to `wp-config.php` to be able to see the jQuery migrate warnings.

> @nielslange According to the link you shared re: `.trim()`, have you tested to see if that change is compatible?

I tested the change and it works as expected and added the change to your PR.

**Comment by rebeccahum** [comment]
@nielslange Have you tested it on `author.id` since that is not a string?

**Comment by nielslange** [comment]
> @nielslange Have you tested it on `author.id` since that is not a string?

I did, and the input variable for `author.id` comes as a string. Adding `console.log(vals);` below https://github.com/Automattic/Co-Authors-Plus/blob/44fd892dc1e06b976dd48de6ba6d0687c7bdcb7b/js/co-authors-plus.js#L196, results in:

Screenshot 2021-07-20 at 09 52 50

Adding `console.log(author);` below https://github.com/Automattic/Co-Authors-Plus/blob/44fd892dc1e06b976dd48de6ba6d0687c7bdcb7b/js/co-authors-plus.js#L208, then results in:

Screenshot 2021-07-20 at 09 58 39

**Comment by rebeccahum** [comment]
Sounds good, thanks for the update 👍

**Review by mikeyarce — APPROVED** [review]
Looks good to me!

**Pull request merged**
