### PR TITLE
use esc_html_e() instead of _e()

### PR DESCRIPTION
**Pull request by paulschreiber**

### CODE REVIEW

**Comment by mjangda** [comment]
Some of the strings have HTML in them (i.e. `<strong>`) and this change would encode those tags when outputting.

**Comment by paulschreiber** [comment]
Good catch. I replaced a few of those calls with `wp_kses_post()`.

**Comment by paulschreiber** [comment]
@mjangda

**Comment by paulschreiber** [comment]
Updated to use `__()` and `wp_kses()`.

**Pull request merged**
