### PR TITLE
Use PHPCS 2.9 for compat with WordPress Coding Standards

### PR DESCRIPTION
**Pull request by trepmal**

### CODE REVIEW

**Comment by trepmal** [comment]
WordPress Coding Standards is not currently compatible with PHPCS 3.0 ([#](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/718))

Using the 2.9 branch, PHPCS now runs. We're not passing, but it runs :P

**Comment by philipjohn** [comment]
It looks like PHPCS is working: https://travis-ci.org/Automattic/Co-Authors-Plus/jobs/240804028

Or am I looking in the wrong place?

**Comment by trepmal** [comment]
Looks like that job doesn't have sniffs enabled, see https://travis-ci.org/Automattic/Co-Authors-Plus/jobs/240804024

**Comment by philipjohn** [comment]
This is failing atm anyway because 5.2 isn't installing :man_facepalming:

**Comment by philipjohn** [comment]
Maybe we should wait until https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/718 gets a resolution?

**Comment by GaryJones** [comment]
WPCS is now compatible with PHPCS 3.0 (including up to the latest 3.3.1), so this PR can be closed unmerged.

**Pull request closed without merging**
